name: Scrape MagicBricks Projects

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python prop.py

    - name: Upload CSV file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: magicbricks_projects
        path: magicbricks_projects.csv

    - name: Upload JSON file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: magicbricks_projects_json
        path: magicbricks_projects.json
